### ISSUE TITLE
Browser usage and poToken

### ISSUE THREAD

**Issue by Elite** [ybd-project-ver1/ytdl-core#17]
When using the library in a userscript, will it use the users default potoken and vistoredata from the current youtube session or utilize a fresh environment for the generation (no external potoken generator is used [only bulit-in](https://github.com/ybd-project-ver1/ytdl-core?tab=readme-ov-file#disable-automatic-potoken-generation) ).

**Comment by ybd-project-ver1** [comment]
Automatic generation is only available for Default, and is not implemented for Browser and Serverless.

**Comment by Elite** [comment]
Thanks

**Comment by Elite** [comment]
BTW, how to specify the innertube client and get premuxed 720p streams like the ones provided by `mediaconnect` client i guess.

**Comment by ybd-project-ver1** [comment]
The clients available for ytdl-core right now are web,webCreator,android,IOS,tv,tvEmbedded,webEmbedded. if you need mediaconnect support, please let us know.

**Comment by Elite** [comment]
Does any client in the above offers the premuxed 720p video, maybe as hls stream?

**Comment by ybd-project-ver1** [comment]
No, I don't think it is included.
