### ISSUE TITLE
TypeError: Reader was released and can no longer be used to monitor the stream's closedness

### ISSUE THREAD

**Issue by AquaChocomint** [ybd-project-ver1/ytdl-core#18]
I got this error:

```
TypeError: Reader was released and can no longer be used to monitor the stream's closedness

at ReadableStreamReaderGenericRelease (node_modules/@ybd-project/ytdl-core/bundle/node.cjs:18:20103)
    at z.releaseLock (node_modules/@ybd-project/ytdl-core/bundle/node.cjs:18:16966)
    at streamToIterable (node_modules/@ybd-project/ytdl-core/bundle/node.cjs:897:916)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async node_modules/@ybd-project/ytdl-core/bundle/node.cjs:897:2885
```

Environments:
Nodejs: v22.9.0
ytdl-core: v6.0.2 (with OAuth2)

**Comment by ybd-project-ver1** [comment]
Thank you for your report. I have not seen this error before, can you tell me what code you are implementing?

**Comment by AquaChocomint** [comment]
```ts
const ytdl: YtdlCore; //with OAuth2 (tokens are extracted with cobalt)
const url: string;

//get information
ytdl.getFullInfo(url);

//audio download
ytdl.download(url, {
            filter: 'audioonly',
            quality: 'highestaudio',
            highWaterMark: 1 << 25,
            dlChunkSize: 0,
            streamType: 'nodejs'
        });
```

**Comment by ybd-project-ver1** [comment]
There seems to be no problem in the code, so we will test it here. We would appreciate it if you could provide us with the URL of the video where the error is occurring.

**Comment by AquaChocomint** [comment]
https://youtu.be/l4OK0f46b_I?si=biLP-eOL1JCKV0Ac, https://youtu.be/7At6BhGOQzo?si=DC8WiRvNZdazOChH

but the log prints
`[JINTER]: JavaScript node "EmptyStatement" not implemented!
If this is causing unexpected behavior, please report it at https://github.com/LuanRT/Jinter/issues/new`
before the issue of "TypeError: Reader was released and can no longer be used to monitor the stream's closedness" occurs.

Perhaps this has nothing to do with ytdl-core?

**Comment by ybd-project-ver1** [comment]
That's okay. We are currently sending an Issue to the appropriate repository for that Jinter problem, and there is no direct problem with ytdl-core's operation.

This TypeError is believed to be an error caused by using WebStreams Polyfill's ReadableStream.

**Comment by AquaChocomint** [comment]
> That's okay. We are currently sending an Issue to the appropriate repository for that Jinter problem, and there is no direct problem with ytdl-core's operation.
> 
> This TypeError is believed to be an error caused by using WebStreams Polyfill's ReadableStream.

thank you for sending the issue.
yeah, i also believe that.

**Comment by ybd-project-ver1** [comment]
We have released v6.0.3 which fixes this problem. Please check it out.

**Comment by AquaChocomint** [comment]
Thank you. it worked!
can i close this issue?

**Comment by ybd-project-ver1** [comment]
> Thank you. it worked!
> can i close this issue?

yes, you can!
