### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by tonykx** [ybd-project-ver1/ytdl-core#2]
For more information, specify YTDL_DEBUG as an environment variable.
Note: This error cannot continue processing. (Details: "Sign in to confirm you’re not a bot")

**Comment by ybd-project-ver1** [comment]
Please give me the details of the error, the version of ytdl-core, and what code you are implementing.

**Comment by tonykx** [comment]
> Por favor, dê-me os detalhes do erro, a versão do ytdl-core e qual código você está implementando.

Estou usando a versão mais recente, o erro é que pede login
Meu código: 
case 'play2': {
if(!q) return reply('Cadê o nome da música?')
  const query = args.join(" "); // Declare a variável query aqui
  try {
    const results = await yts(query).catch(() => null);
    if (!results || !results.all || results.all.length === 0) {
      throw new Error('Nenhum resultado encontrado com a biblioteca yts.');
    }

    const firstResult = results.all[0];
    const caption = `🎵 Título: ${firstResult.title}\n` +
                    `⌛ Duração: ${firstResult.timestamp}\n` + 
                    `ℹ️ Descrição: ${firstResult.description || 'Sem descrição disponível.'}`;

    await conn.sendMessage(from, { image: { url: firstResult.thumbnail }, caption }, { quoted: info });

    // Função para download com ytdl
    const downloadYTDL = async () => {
      const videoInfo = await ytdl.getInfo(`https://youtube.com/watch?v=${firstResult.videoId}`);

      const audioFormat = ytdl.chooseFormat(videoInfo.formats, { quality: 'lowestaudio' });
      const stream = ytdl.downloadFromInfo(videoInfo, { filter: "audioonly", format: audioFormat });

      const vidName = await getRandom('.mp3');
      const path = `Del/${vidName}`;
      const writer = fs.createWriteStream(path);
      stream.pipe(writer);

      return new Promise((resolve, reject) => {
        writer.on("finish", async () => {
          console.log("Download Completed!");
          await conn.sendMessage(from, { audio: { url: path }, mimetype: "audio/mpeg" }, { quoted: info });
          await fs.unlinkSync(path);
          resolve();
        });

        writer.on("error", reject);
      });
    };

    // Executa o download
    await downloadYTDL();

  } catch (error) {
    console.error("Erro:", error.message);

**Comment by ybd-project-ver1** [comment]
How is ytdl defined?

**Comment by tonykx** [comment]
> Como o ytdl é definido?

Estou usando a que está na documentação, com o final /old

**Comment by ybd-project-ver1** [comment]
What environment is this running in?

**Comment by tonykx** [comment]
> Em que ambiente isso está ocorrendo?

Bitnami

**Comment by ybd-project-ver1** [comment]
Sorry for the late reply, you mean Bitnami.
The only way you can try now is to try OAuth2, specify a PoToken or something similar, or physically change the location of the server.

**Comment by tonykx** [comment]
> Desculpe pela resposta tardia, você quer dizer Bitnami. A única maneira de tentar agora é tentar o OAuth2, especificar um PoToken ou algo semelhante ou alterar fisicamente o local do servidor.

Friend, please can you adapt it to my case, how it works with Oauth2? Put a dummy token and I'll edit it.

**Comment by ybd-project-ver1** [comment]
To implement OAuth2, do the following
```ts
import ytdlCore from '@ybd-project/ytdl-core/old';

ytdlCore.getFullInfo("https://www.youtube.com/watch?v=ID", {
    oauth2: ytdlCore.OAuth2({
         accessToken: 'ACCESS_TOKEN',
         refreshToken: 'REFRESH_TOKEN',
        expiryDate: 'yyyy-MM-ddThh-mm-ssZ',
    }),
}).then(console.log).catch(console.error)
```

**Comment by tonykx** [comment]
Mano estou tendo esse erro:  ytdl.OAuth2 is not a constructor

**Comment by Toidi357** [comment]
what's the issue right now with generated potoken/visitordata still getting the "sign in to confirm" error

**Comment by ybd-project-ver1** [comment]
> what's the issue right now with generated potoken/visitordata still getting the "sign in to confirm" error

Recently, the PoToken specification has been changed or an error occurs. (It works locally, but...)

**Comment by ybd-project-ver1** [comment]
> Mano estou tendo esse erro: ytdl.OAuth2 is not a constructor

I forgot to add `new` at OAuth2.

```ts
import ytdlCore from '@ybd-project/ytdl-core/old';

ytdlCore.getFullInfo("https://www.youtube.com/watch?v=ID", {
    oauth2: new ytdlCore.OAuth2({
         accessToken: 'ACCESS_TOKEN',
         refreshToken: 'REFRESH_TOKEN',
        expiryDate: 'yyyy-MM-ddThh-mm-ssZ',
    }),
}).then(console.log).catch(console.error)
```
