### ISSUE TITLE
Property 'pipe' does not exist on type 'YTDL_NodejsStreamType'

### ISSUE THREAD

**Issue by arcovoltaico** [ybd-project-ver1/ytdl-core#26]
## Describe the bug
Using the example:
    const ytdl = new YtdlCore({
      // The options specified here will be the default values when functions such as getFullInfo are executed.
    });

    ytdl
      .download('https://www.youtube.com/watch?v=dQw4w9WgXcQ', {
        streamType: 'nodejs', // Note: If you do not set the `streamType` to `nodejs`, a pipable stream will not be returned.
      })
      .then((stream) => stream.pipe(fs.createWriteStream('video.mp4')));

## Error Details (Log)
TS2339: Property 'pipe' does not exist on type 'YTDL_NodejsStreamType'.
## Environment

- Video URL:
- @ybd-project/ytdl-core version: latest
- Node.js version: 20.x
- Operating system: macOs Sequoia

**Comment by ybd-project-ver1** [comment]
Thank you for your report. Basically, if you specify `streamType: 'nodejs'`, the ReadableStream should be successfully converted to a pipeable Stream. We will investigate this issue here as it is most likely a code issue.
If you can provide more information, please do so.

**Comment by ybd-project-ver1** [comment]
If no reply is received within 2 days of this comment, this issue will be closed.
