### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by arcovoltaico** [ybd-project-ver1/ytdl-core#27]
I needed to add this to the Ytdl.ts to be able to run my app:

export interface UnderlyingByteSource {
    start?: (controller: ReadableStreamDefaultController) => void | Promise<void>;
    pull?: (controller: ReadableStreamDefaultController) => void | Promise<void>;
    cancel?: (reason: any) => void | Promise<void>;
}
export interface UnderlyingDefaultSource<R> {
  start?: (controller: ReadableStreamDefaultController<R>) => void | Promise<void>;
  pull?: (controller: ReadableStreamDefaultController<R>) => void | Promise<void>;
  cancel?: (reason: any) => void | Promise<void>;
}

## Environment

- @ybd-project/ytdl-core version: latest
- Node.js version: 20.x
- Operating system: macOs Sequoia

**Comment by ybd-project-ver1** [comment]
What specific build errors are you experiencing?
