### ISSUE TITLE
The token is not renewed upon expiry

### ISSUE THREAD

**Issue by hydragenesis** [ybd-project-ver1/ytdl-core#28]
I have specified oauth2 token + client data in my code, but it stops working after the token expires. It does not renew. Can you tell me how to set it up? Like where the renewed token will be saved? Will it be modified in my script?

## Environment

- Video URL:
- @ybd-project/ytdl-core version: 6.0.4
- Node.js version: 16.20.0
- Operating system: Windows 10 Sever

**Comment by ybd-project-ver1** [comment]
Thank you for your report, OAuth2 is basically judged by the expiration date specified, and if the expiration date has passed, the renewal process is executed. However, if the information required for renewal cannot be obtained for some reason, the renewal will not be executed normally.
Also, please check the debug log. we will investigate the code here as well.

**Comment by hydragenesis** [comment]
Will the token be updated in my script? Can I specify where the refresh token can be saved? Like I want the refreshed oauth2 details to be save in a json file.

**Comment by ybd-project-ver1** [comment]
At this time, the updated OAuth2 is stored in the .CacheFiles folder if file caching is enabled. File cache is disabled in the browser version.
Note that the path to this folder is as follows
For Default: node_modules/@ybd-project/ytdl-core/package/platforms/Default/.CacheFiles/
For serverless version: (temp folder path)/.YtdlCore-Cache/

**Comment by ybd-project-ver1** [comment]
If no reply is received within 2 days of this comment, this issue will be closed.
