### ISSUE TITLE
Issue start ing app using ytdl-core

### ISSUE THREAD

**Issue by paradix** [ybd-project-ver1/ytdl-core#3]
I'm getting this error on a clean install. 
Can you maybe help with that? 
`
Error: Cannot find module '/opt/test/node_modules/@ybd-project/ytdl-core/package/Platforms/Default/Default.js'`

**Comment by tonykx** [comment]
Recentemente recebi um erro que diz que não é possível adicionar qualidade de áudio, "lowestaudio"

**Comment by ybd-project-ver1** [comment]
This problem occurs in v5.1.9. (I made a mistake when I published it.)
Please try installing v5.1.9-2.
