### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by tonykx** [ybd-project-ver1/ytdl-core#7]
Estou tendo esse ao tentar gerar o PoToken, essa é minha função:
//função
case 'po':
    async function extractYouTubeData() {
        const videoId = "kJQP7kiw5Fk"; 
        try {
            const { scrapeYouTubeData } = await import("youtube-scraper-data");
            const data = await scrapeYouTubeData(videoId);
            const poToken = data.poToken; 
            const visitorData = data.visitorData;
            console.log(`PO_TOKEN: ${poToken}`);
            console.log(`VISITOR_DATA: ${visitorData}`);
        } catch (error) {
            console.error("Erro ao extrair dados:", error);
        }
    }
    extractYouTubeData();
    break;

Abaixo vou deixar o erro que estou tendo:
//Error
TypeError: http_proxy_agent_1.HttpProxyAgent.protocols is not iterable
    at Object.<anonymous> (/home/bitnami/bot/node_modules/proxy-agent/dist/index.js:43:42)
    at async extractYouTubeData (/home/bitnami/bot/index.js:2976:43)

**Comment by ybd-project-ver1** [comment]
_This error is a problem with the package you are using (youtube-scraper-data).
However, one thing I can tell you is that you should not use JavaScript to generate PoToken, but rather generate them from the command line. Please check the README of each repository for details on how to generate them._

**Comment by tonykx** [comment]
> Este erro é um problema com o pacote que você está usando (youtube-scraper-data). No entanto, uma coisa que posso dizer é que você não deve usar JavaScript para gerar PoToken, mas sim gerá-los a partir da linha de comando. Verifique o README d Dude, I didn't understand that readme, can you leave the commands here for me to execute, like you did in the Oauth2 example?e cada repositório para obter detalhes sobre como gerá-los.

**Comment by tonykx** [comment]
> Este erro é um problema com o pacote que você está usando (youtube-scraper-data). No entanto, uma coisa que posso dizer é que você não deve usar JavaScript para gerar PoToken, mas sim gerá-los a partir da linha de comando. Verifique o README de cada repositório para obter detalhes sobre como gerá-los.

Cara, eu não entendi esse leia-me, você pode deixar os comandos aqui para eu executar, como você fez no exemplo do Oauth2?e cada repositório para obter detalhes sobre como gerá-los.

**Comment by ybd-project-ver1** [comment]
1. git clone https://github.com/fsholehan/scrape-youtube
2. cd scrape-youtube
3. npm i
4. npm start

That is all.

**Comment by tonykx** [comment]
> 1. `git clone https://github.com/fsholehan/scrape-youtube`
> 2. `cd scrape-youtube`
> 3. `npm i`
> 4. `npm start`
> 
> Isso é tudo

Obtive esse erro após o `npm start`:

youtube-scraper-data@1.1.2 start
> node index.js
file:///home/bitnami/scrape-youtube/node_modules/@puppeteer/browsers/lib/esm/launch.js:301
                reject(new Error([
                       ^
Error: Failed to launch the browser process!
/root/.cache/puppeteer/chrome/linux-127.0.6533.99/chrome-linux64/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://pptr.dev/troubleshooting
    at Interface.onClose (file:///home/bitnami/scrape-youtube/node_modules/@puppeteer/browsers/lib/esm/launch.js:301:24)

**Comment by ybd-project-ver1** [comment]
An error will occur if the browser is not available. However, v6.0.1 released yesterday will probably automatically generate a normal PoToken, so please try that.

**Comment by tonykx** [comment]
> Ocorrerá um erro se o navegador não estiver disponível. No entanto, a v6.0.1 lançada ontem provavelmente gerará automaticamente um PoToken normal, então tente isso.

Preciso atualizar?

**Comment by tonykx** [comment]
Qual comando uso pra atualizar a biblioteca

**Comment by ybd-project-ver1** [comment]
> Qual comando uso pra atualizar a biblioteca

npm i @ybd-project/ytdl-core@latest

**Comment by tonykx** [comment]
> > Qual comando uso pra atualizar a biblioteca
> 
> npm i @ybd-projeto/ytdl-core@latest

npm error 404 Not Found - GET https://registry.npmjs.org/@ybd-projeto%2fytdl-core - Not found
npm error 404
npm error 404  '@ybd-projeto/ytdl-core@latest' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-07T01_02_06_058Z-debug-0.log

**Comment by ybd-project-ver1** [comment]
Please copy as is.
The name is “ybd-projecto”.

**Comment by tonykx** [comment]
> Por favor, copie como está. O nome não é "ybd-projecto".

Olha aí amigo 

/bitnami/bot# npm i @ybd-projeto/ytdl-core@latest
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@ybd-projeto%2fytdl-core - Not found
npm error 404
npm error 404  '@ybd-projeto/ytdl-core@latest' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-07T01_16_18_300Z-debug-0.log

**Comment by ybd-project-ver1** [comment]
Run "npm i @ybd-project/ytdl-core@latest" instead of "npm i @ybd-projeto/ytdl-core@latest".

**Comment by tonykx** [comment]
> Execute "npm i @ybd-project/ytdl-core@latest" em vez de "npm i @ybd-projeto/ytdl-core@latest".

Estou tendo esse erro:

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './old' is not defined by "exports" in /home/bitnami/bot/node_modules/@ybd-project/ytdl-core/package.json

**Comment by ybd-project-ver1** [comment]
Starting with v6.0.0, the /old usage is obsolete.

**Comment by tonykx** [comment]
> A partir da v6.0.0, o uso /old está obsoleto.

Agora está dando isso: 

Ocorreu um erro: TypeError: ytdl.OAuth2 is not a constructor

**Comment by tonykx** [comment]
Quando retiro Oauth2, tenho esse erro:

const ytdl = new YtdlCore({ disablePoTokenAutoGeneration: true }); is not a constructor
